# in _config.yml
title: ""
logo: images/logo_ib_maths.png
only_build_toc_files: true
execute:
  execute_notebooks: "force"
sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
